# Generated by Django 4.2.2 on 2023-07-12 01:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('contrasena', models.CharField(max_length=8)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, default='user/default_user.jpg', null=True, upload_to='media/user')),
                ('estado', models.BooleanField(default=True)),
                ('online', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='resumen',
        ),
        migrations.AddField(
            model_name='articulo',
            name='bajada',
            field=models.CharField(default='Sin bajada', max_length=600),
        ),
        migrations.AddField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='actualizacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='categoria',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, default='articulo/default_articulo.jpg', null=True, upload_to='media/articulo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='articulo',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articulo.user'),
        ),
    ]
